### ISSUE TITLE
In app bug reporting

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationKeyboard#26]
We need an in app method of reporting bugs and crash reports. Currently, there is no effective method of giving the devs the information they need.

**Comment by neutrinog** [comment]
I've almost finished abstracting all the error reporting into reusable classes.

**Comment by neutrinog** [comment]
@bknatterud @PeeJWeeJ  I've created an android module for logging, handling crashes, and submitting issue to github.You can find it at https://github.com/unfoldingWord-dev/ts-android/tree/develop/com.door43.tools.reporting.

I'm not familiar with your code at all so it may be faster to let one of you integrate this. I'm also not sure how we want to handle code like this. we could throw it into it's own repo and make it a github module so it's easy to send out updates.

Let me know if you need help.

**Comment by bknatterud** [comment]
ok, we will take a look at it on Friday.

**Comment by bknatterud** [comment]
We will add this bug reporting into the app in the next two days.

**Comment by neutrinog** [comment]
cool. Let me know if you need to make any changes to the code. I'd like to eventually maintain a separate repository with generic tools that can be shared between apps.

**Comment by PeeJWeeJ** [comment]
I was able to get most everything I needed from the tS repo, but I didn't find anything related to finding/setting the OAuth key necessary for github submission. From what I found, it's using "github_oauth2" in "dummy_strings_private_app_pref" which, as far as I can tell, is never changed from the default

How is this being handled?

**Comment by neutrinog** [comment]
@PeeJWeeJ I may not completely understand your question.
The oauth2 token is passed to the `GithubReporter` constructor. As for storing it, I have been placing the value in a string resource. 

In order to prevent others from getting a hold of the production token (because all the code is publicly available) I place the string resource in it's own file e.g. `src/main/res/values/private_strings.xml` or something like that. That file is then added to the `.gitignore` file.

Furthermore, so that other developers can develop and build the code without things breaking when it can't find the oauth2 token (because it's ignored by git) I add in some conditional code checking if the resource exists before I try to use it.

e.g.
```java
int githubTokenIdentifier = getResources().getIdentifier("github_oauth2", "string", getPackageName());
if(githubTokenIdentifier != 0) {
   String oauth2 = getResources().getString(githubTokenIdentifier);
}
```

**Comment by PeeJWeeJ** [comment]
@neutrinog I think that mostly answers my question.

What account are you using for the token? The GitHub API indicates only users with pull access can submit issues and it doesn't seem like a good idea to use my own account.

**Comment by neutrinog** [comment]
@PeeJWeeJ we are using https://github.com/door43app for creating issues. Are you on slack? I can send you a token there.

**Comment by PeeJWeeJ** [comment]
Ok. @jag3773 Can you add me to slack?

**Comment by PeeJWeeJ** [comment]
@neutrinog my username on Slack is PJ_Fechner

**Comment by PeeJWeeJ** [comment]
This is implemented in the most recent beta
